### ISSUE TITLE
cannot retrieve contact details.

### ISSUE THREAD

**Issue by Ashwin3454** [joe444-pnj/saintgram#1]
<img width="382" alt="image" src="https://github.com/user-attachments/assets/bd4216d6-7849-4f59-82b2-be64b720f7fc">

**Comment by joe444-pnj** [comment]
Hi Ashwin3454,

Thanks for reaching out and sharing the screenshot! To better understand the issue you're facing, could you please clarify a few things for me:

What specific issue are you encountering?
Is the tool not fetching the correct information, or are there any fields missing or incorrect in the output?

Did you follow the installation steps exactly as described in the README?

For example, cloning the repo, installing dependencies, and obtaining the sessionID correctly.

Are you getting any error messages or exceptions when running the tool?
 If so, could you provide the error log or the output of the terminal when it fails?

Have you tried running the tool with different Instagram accounts?
Sometimes, API restrictions or session issues could block certain accounts.

Is the target account you’re trying to scrape a private account?
If yes, remember the tool works only if you are friends with the victim account.

Let me know the answers to these, and I’ll be happy to assist further!
